# qtlite/core/enums.py
from __future__ import annotations

from enum import Enum, auto


class Frequency(Enum):
    """Data / rebalancing frequency."""
    DAILY = auto()
    WEEKLY = auto()
    MONTHLY = auto()


class PositionSide(Enum):
    """Portfolio direction."""
    LONG_ONLY = auto()
    SHORT_ONLY = auto()
    LONG_SHORT = auto()
    MARKET_NEUTRAL = auto()


class ReturnType(Enum):
    """Type of returns used in backtests."""
    SIMPLE = auto()
    LOG = auto()


class SignalType(Enum):
    """Signal type generated by a strategy."""
    SCORE = auto()      # arbitrary score (higher = better)
    RANK = auto()       # cross-sectional rank
    WEIGHT = auto()     # target portfolio weight
